MONGODB_HOST: mongodb-{{ env }}.ramvootukuri.com
REDIS_HOST: redis-{{ env }}.ramvootukuri.com
MYSQL_HOST: mysql-{{ env }}.ramvootukuri.com 
RABBITMQ_HOST: rabbitmq-{{ env }}.ramvootukuri.com 
CATALOGUE_HOST: catalogue-{{ env }}.ramvootukuri.com
USER_HOST: user-{{ env }}.ramvootukuri.com
CART_HOST: cart-{{ env }}.ramvootukuri.com
SHIPPING_HOST: shipping-{{ env }}.ramvootukuri.com
PAYMENT_HOST: payment-{{ env }}.ramvootukuri.com